packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.13.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  node20:
    "@types/node": "^20.16.11"
  node22:
    "@types/node": "^22.13.10"
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  next14:
    "next": "^14.2.15"
  env:
    "dotenv-cli": "^7.4.2"
    "@t3-oss/env-nextjs": "^0.11.1"
    "@t3-oss/env-core": "^0.11.1"
  prisma:
    "prisma": "^5.22.0"
    "@prisma/client": "^5.22.0"
    "@prisma/nextjs-monorepo-workaround-plugin": "^5.22.0"
  vitest:
    "vitest": "^2.1.8"
    "@vitejs/plugin-react": "^4.3.4"
    "@vitest/coverage-v8": "^2.1.8"
    "@vitest/ui": "^2.1.8"
  rtl:
    "jsdom": "^25.0.1"
    "@testing-library/jest-dom": "^6.6.3"
    "@testing-library/react": "^16.1.0"
    "@testing-library/user-event": "^14.5.2"
  ui:
    "lucide-react": "^0.456.0"
    "next-themes": "^0.4.4"
    "react-hook-form": "^7.54.2"
    "sonner": "^1.7.1"
    "@hookform/resolvers": "^3.10.0"
    "@tanstack/react-table": "^8.20.6"
  uuid:
    "uuid": "^10.0.0"
    "@types/uuid": "^10.0.0"
  liveblocks:
    "@liveblocks/client": "^2.8.2"
    "@liveblocks/node": "^2.8.2"
    "@liveblocks/react": "^2.8.2"
    "@liveblocks/yjs": "^2.8.2"
