name: Playwright Tests
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Build app
        run: pnpm -F worxpace build

      - name: Run Playwright tests
        run: pnpm -F worxpace t

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
